export const DASHBOARD = '/instagram-clone'
export const LOGIN = '/instagram-clone/login'
export const SIGN_UP = '/instagram-clone/sign-up'
export const PROFILE = '/instagram-clone/p/:username'
export const NOT_FOUND = '/instagram-clone/not-found'
